### ISSUE TITLE
[Bug]: Remix esbuild fails with "could not resolve" errors for rvf packages

### ISSUE THREAD

**Issue by bravo-kernel** [airjp73/rvf#373]
### Which packages are impacted?

- [ ] `@rvf/react`
- [X] `@rvf/remix`
- [X] `@rvf/zod`
- [ ] `@rvf/yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- @rvf/remix": "^6.0.0"
- @rvf/zod": "^6.0.0"

### Please provide a link to a minimal reproduction of the issue.

https://private.repo.com

### Steps to Reproduce the Bug or Issue

Replaced remix-validated-form with rvf.

### Expected behavior

As a user I expected `npm run dev` to start without errors.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/46ca992f-4081-4dca-b0ba-6c1703e89f84)

### Platform

- OS: Windows
- Node v20.16.0
- Remix 2.10.3
- - Browser: N/A

### Additional context

Console output after running `npm run dev`

```bash
✘ [ERROR] Build failed with 3 errors:
node_modules/@rvf/react/dist/index.esm.js:5:7: ERROR: Could not resolve "@rvf/core"
node_modules/@rvf/react/dist/index.esm.js:28:7: ERROR: Could not resolve "@rvf/set-get"
node_modules/@rvf/zod/dist/index.esm.js:2:32: ERROR: Could not resolve "@rvf/core" [plugin css-bundle-plugin]

    app/routes/admin+/_layout.tsx:20:30:
      20 │ import { cssBundleHref } from "@remix-run/css-bundle";
         ╵                               ~~~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onLoad" callback registered here:

    node_modules/@remix-run/dev/dist/compiler/plugins/cssBundlePlugin.js:35:12:
      35 │       build.onLoad({
         ╵             ~~~~~~

    at setup (D:\repo\node_modules\@remix-run\dev\dist\compiler\plugins\cssBundlePlugin.js:35:13)
    at handlePlugins (D:\repo\node_modules\esbuild\lib\main.js:1279:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


✘ [ERROR] Could not resolve "@rvf/core"

    node_modules/@rvf/react/dist/index.esm.js:5:7:
      5 │ } from "@rvf/core";
        ╵        ~~~~~~~~~~~

  You can mark the path "@rvf/core" as external to exclude it from the bundle, which will remove this error.


✘ [ERROR] Could not resolve "@rvf/set-get"

    node_modules/@rvf/react/dist/index.esm.js:28:7:
      28 │ } from "@rvf/set-get";
         ╵        ~~~~~~~~~~~~~~

  You can mark the path "@rvf/set-get" as external to exclude it from the bundle, which will remove this error.


✘ [ERROR] Could not resolve "@rvf/core"

    node_modules/@rvf/zod/dist/index.esm.js:2:32:
      2 │ import { createValidator } from "@rvf/core";
        ╵                                 ~~~~~~~~~~~

  You can mark the path "@rvf/core" as external to exclude it from the bundle, which will remove this error.
```

**Comment by airjp73** [comment]
Hi! Thank you for reporting the issue.

Unfortunately, I won't be able to help much without a reproduction as I'm not able to reproduce it myself.

Some references on minimal reproductions:
- [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)
- [wtf-is-a-minimal-reproduction](https://minimum-reproduction.wtf/#:~:text=There's%20a%20few%20reasons%20to,to%20dig%20through%20and%20understand)

In the meantime, some things worth trying on your end:
- Try installing those packages directly
- Try deleting node_modules and your lockfile and re-installing
- Mark those packages as external in the remix config

**Comment by bravo-kernel** [comment]
Yes I understand. Option 2 does not resolve the issue. Options 1 and 2 should work but that's basically why I created the ticket, not the unexpected behavior. I will see if I can create a reproduction.

**Comment by bravo-kernel** [comment]
Closing as I cannot reproduce. Much appreciated, v6 is ❤️
