### ISSUE TITLE
[Feature]: Support name/value on button components

### ISSUE THREAD

**Issue by michaelgmcd** [airjp73/rvf#401]
### What is the new or updated feature that you are suggesting?

This may already be supported, but I'd like to include a value provided by a button component in a form submission. If it's not already supported, I can look into opening a PR, but would appreciate some guidance.

```typescript
const Component = () => {
  // ...

  return (
    <form {...form.getFormProps()}>
      <button name="someName" value="someValue" />
    </form>
  );
}
```

### Why should this feature be included?

It's a very common use case for passing different values based on what button a user clicks.

**Comment by airjp73** [comment]
This should already work, so there might be a bug. Are you able to provide a reproduction?

**Comment by michaelgmcd** [comment]
Looks like an issue on my end. The repro seems to work. A helper like `form.getButtonProps()` may be useful, but I'm unblocked for now.
