### ISSUE TITLE
[Feature]: React 19 support in rvf/remix

### ISSUE THREAD

**Issue by stevensacks** [airjp73/rvf#406]
### What is the new or updated feature that you are suggesting?

Adding support for React 19 (by switching to react-router 7).

When you try to install React 19, you get this error. Using `--legacy-peer-deps` will silence it for now.
```
npm error Found: react@19.0.0
npm error node_modules/react
npm error   react@"19.0.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^18.0.0" from @remix-run/react@2.15.1
npm error node_modules/@remix-run/react
npm error   peer @remix-run/react@">= 1.15.0" from remix-validated-form@5.1.5
npm error   node_modules/remix-validated-form
npm error     peer remix-validated-form@"^4.x || ^5.x" from @remix-validated-form/with-zod@2.0.7
npm error     node_modules/@remix-validated-form/with-zod
npm error       @remix-validated-form/with-zod@"2.0.7" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

### Why should this feature be included?

- Remix is migrating everyone to React Router 7
- React 19 is stable

**Comment by ivogt** [comment]
I am also looking forward to resolving the react 19 compatibility.

**Comment by airjp73** [comment]
I got most of the work for this done today, so hopefully it shouldn't be too much longer.

**Comment by airjp73** [comment]
I've released support for React 19 and RR 7 as v7. https://github.com/airjp73/rvf/releases/tag/v7
